name: Keep the repo alive
on:
  schedule:
    - cron: "45 22 * * *"
  push:
  fork:
  status:
  issues:

jobs:
  keep_alive:
    name: Keep alive github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@v1
        with:
          committer_username: ${GITHUB_ACTOR}
          committer_email: ${GITHUB_ACTOR}@users.noreply.github.com
